[[section-solution-strategy]]
== Solution Strategy

Due to the social content of the application and other solid apps that we've seen we decided that
the best option is to do it in a web enviroment and run it on a server so it's more user-friendly.
At the moment the plan for our application structure is based on a JavaScript application with HTML components that follow solid's style guide and pattern in the app apearence.

For the teamwork, project development and documentation we'll be using a GitHub repository to keep things in order.

Decisions taken about the chat:

* Solid: by subject requirements.
* Solid-file-client: a library for creating and managing files and folders in Solid data stores.
* Webpack: bundle JavaScript files for usage in a browser.
* Node.js: JavaScript runtime built on Chrome's V8 JavaScript engine.
* Bootstrap: open source toolkit for designing web sites.
* GitHub: also by subject requierements.
* AsciidocFX: Asciidoc document editor to perform the documentation.


